x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME}
  env_file: .env
  environment:
    - DBT_PROFILES_DIR=/opt/airflow/dbt_project
  volumes:
    - ${AIRFLOW_PROJ_DIR}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR}/files:/opt/airflow/files    
    - ${AIRFLOW_PROJ_DIR}/logs:/opt/airflow/logs      
    - ${AIRFLOW_PROJ_DIR}/config:/opt/airflow/config  
    - ${AIRFLOW_PROJ_DIR}/plugins:/opt/airflow/plugins
    - ./dbt_project:/opt/airflow/dbt_project
    - ./data_lake:/opt/airflow/data_lake
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file: .env
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/pg_files:/files
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - lake
    restart: always

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    container_name: airflow-init
    command: >
      -c "
      airflow db migrate &&
      airflow users create --username $${AIRFLOW_WWM_USER_USERNAME} --password $${AIRFLOW_WWM_USER_PASSWORD} --firstname Israfil --lastname Ismayilov --role Admin --email admin@local &&
      airflow variables import /opt/airflow/files/variables.json
      "
    networks:
      - lake
    user: "0:0"
    volumes:
      - ${AIRFLOW_PROJ_DIR}:/sources
      - ${AIRFLOW_PROJ_DIR}/files:/opt/airflow/files
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    container_name: airflow-webserver
    networks:
      - lake
    ports:
      - "8080:8080"
      - "8055:8055"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: airflow-scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - lake
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

volumes:
  airflow:
  pgdata:
  pg_files:

networks:
  lake:
    driver: bridge